### ISSUE TITLE
About the process of MRI slices

### ISSUE THREAD

**Issue by IRIS00123** [aditya-gupta-i/BicephNet-for-AD-classification#1] opened 2022-09-27 09:05 UTC
Hello, I have recently read your paper "Biceph-Net: A robust and lightweight framework for the diagnosis of Alzheimer’s disease using 2D-MRI scans and deep similarity learning". Your work is very meaningful. Could you please share the code for the process of data slices? 
Thank you very much!

**Comment by aditya-gupta-i** [comment] 2022-09-27 09:29
Duplicate of https://github.com/mtanveer1/BicephNet-for-AD-classification/issues/1
Will be resolved swiftly

**Closed as completed by aditya-gupta-i** 2022-09-27 09:29 UTC
